version: "3.8"
services:
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: biosqldb
    ports:
      - "3306:3306"

  bug-repro:
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    links:
      - mysql
